name: Build and Push Docker Image to GCR

on:
  push:
    branches:
      - feature-branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'

    - name: Configure Docker for GCR
      run: |
        gcloud auth configure-docker

    - name: Build Docker image
      run: |
        docker build -t LOCATION-docker.pkg.dev/${{ secrets.PROJECT_ID }}/weather-api .

    - name: Push to GCR
      run: |
        docker push LOCATION-docker.pkg.dev/${{ secrets.PROJECT_ID }}/weather-api
